version: '3.8'

services:
  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    command: ["listen", "--forward-to", "http://host.docker.internal:8080/payment//appointment-booking/stripe-webhook"]
    environment:
      - STRIPE_API_KEY=sk_test_51Q05VfIPkL7AzL0UcmvPXBprMrwYmS7P163bCMjwWZkgVvQI7WEYRKQnR5nmCVnEP0DhRm1ayI7twKKtb9ablwVM00VGnvSuWo
    ports:
      - "12111:12111"
    volumes:
      - ./stripe-config:/root/.config/stripe
